### ISSUE TITLE
possible issue with the buy and sell functions in the predictionmarket contract

### ISSUE THREAD

**Issue by ResourceHog** [josiahwood/futarchy#1]
I noticed that odds can be set to 0 and values higher than 100. This would result in division by 0 or (I assume) unexpected negative values.

**Comment by josiahwood** [comment]
Good point.  Valid values should be from 1-99.  What is the best way to handle invalid arguments in Ethereum contracts?

Just return while doing nothing?
Clamp the arguments to valid values if possible?
Is there any way for me to notify the caller of their error?
Can I throw an exception that will propagate up the call stack?
Should I return a boolean value indicating success?

I'm not sure what the best practices are at this point.  Thanks for your feedback!

**Comment by josiahwood** [comment]
This article seems to indicate that exceptions are a planned feature, but not available yet.  https://github.com/ethereum/wiki/wiki/Solidity-Features.  Although I'm not sure if this is a Solidity limitation or an EVM one.
